spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manager?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123yhd.

  redis:
    host: 127.0.0.1
    jedis:
      pool:
        min-idle: 5
        max-active: 20
        max-idle: 15


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.handsomedong.manager.entity

logging:
  level:
    com.handsomedong.manager: debug
  file:
    path: ./logs